export type Product = {
  id: string;
  slug: string;
  name: string;
  tamilName?: string;
  category: "oils" | "dryfruits" | "palm-products" | "honey" | "millets";
  description: string;
  image?: string;
  imageAlt?: string;
  variants: { size: string; price: number; stock?: number }[];
  tags?: string[];
  stock?: number;
  price?: number;
  sku?: string;
  enabled?: boolean;
  rating?: number;
  metaTitle?: string;
  metaDescription?: string;
  structuredData?: Record<string, unknown>;
};

export const PRODUCTS: Product[] = [
  // ── Cold Pressed Oils ────────────────────────────────────────────────────────
  {
    id: "10000000-0000-0000-0000-000000000001",
    slug: "groundnut-oil",
    name: "Groundnut Oil",
    tamilName: "கடலை எண்ணெய்",
    category: "oils",
    description:
      "Traditional cold-pressed groundnut oil extracted without chemicals. Rich in antioxidants and perfect for everyday cooking.",
    image: "https://i.ibb.co/tM14KvL4/Chat-GPT-Image-Jun-24-2026-03-53-07-PM.png",
    variants: [
      { size: "500 ml", price: 120, stock: 0 },
      { size: "1 Litre", price: 240, stock: 0 },
    ],
    tags: ["Best Seller", "Popular"],
    price: 120,
    stock: 0,
    sku: "groundnut-oil",
    enabled: true,
  },
  {
    id: "10000000-0000-0000-0000-000000000002",
    slug: "sesame-oil",
    name: "Sesame Oil",
    tamilName: "நல்லெண்ணெய்",
    category: "oils",
    description:
      "Wood-pressed sesame oil rich in calcium, vitamins and healthy fats. Ideal for cooking and traditional uses.",
    image: "https://i.ibb.co/bMdwm3v9/Image-1-1.webp",
    variants: [
      { size: "500 ml", price: 190, stock: 0 },
      { size: "1 Litre", price: 370, stock: 0 },
    ],
    tags: ["Popular"],
    price: 190,
    stock: 0,
    sku: "sesame-oil",
    enabled: true,
  },
  {
    id: "10000000-0000-0000-0000-000000000003",
    slug: "coconut-oil",
    name: "Coconut Oil",
    tamilName: "தேங்காய் எண்ணெய்",
    category: "oils",
    description:
      "Pure cold-pressed coconut oil from fresh coconuts. Excellent for cooking, skin care and hair care.",
    image: "https://i.ibb.co/pBSC9w8t/Chat-GPT-Image-Jun-24-2026-07-00-57-PM.png",
    variants: [
      { size: "500 ml", price: 200, stock: 0 },
      { size: "1 Litre", price: 390, stock: 0 },
    ],
    tags: ["New"],
    price: 200,
    stock: 0,
    sku: "coconut-oil",
    enabled: true,
  },
  {
    id: "10000000-0000-0000-0000-000000000004",
    slug: "castor-oil",
    name: "Castor Oil",
    tamilName: "ஆமணக்கு எண்ணெய்",
    category: "oils",
    description: "Natural castor oil known for hair growth and medicinal benefits.",
    image: "https://i.ibb.co/7d71yWkt/Chat-GPT-Image-Jun-25-2026-10-17-30-AM.png",
    variants: [
      { size: "250 ml", price: 90, stock: 0 },
    ],
    tags: ["Natural"],
    price: 90,
    stock: 0,
    sku: "castor-oil",
    enabled: true,
  },
  {
    id: "10000000-0000-0000-0000-000000000005",
    slug: "mustard-oil",
    name: "Mustard Oil",
    tamilName: "கடுகு எண்ணெய்",
    category: "oils",
    description: "Traditional mustard oil rich in omega fatty acids with natural flavour.",
    image: "https://i.ibb.co/cS2NX06C/Chat-GPT-Image-Jun-25-2026-06-43-30-PM.png",
    variants: [
      { size: "250 ml", price: 75, stock: 0 },
    ],
    tags: ["Traditional"],
    price: 75,
    stock: 0,
    sku: "mustard-oil",
    enabled: true,
  },
  {
    id: "10000000-0000-0000-0000-000000000006",
    slug: "neem-oil",
    name: "Neem Oil",
    tamilName: "வேப்ப எண்ணெய்",
    category: "oils",
    description: "100% pure neem oil for agricultural and external applications.",
    image: "https://i.ibb.co/tw2NqHCD/Chat-GPT-Image-Jun-25-2026-06-35-55-PM.png",
    variants: [
      { size: "250 ml", price: 100, stock: 0 },
    ],
    tags: ["Organic"],
    price: 100,
    stock: 0,
    sku: "neem-oil",
    enabled: true,
  },
  {
    id: "10000000-0000-0000-0000-000000000007",
    slug: "deepam-oil",
    name: "Deepam Oil",
    tamilName: "தீபம் எண்ணெய்",
    category: "oils",
    description: "Traditional deepam oil for ritual and everyday uses, made with care for ceremonial lighting.",
    image: "https://i.ibb.co/gZY8TM8M/remove-the-seed-image-Rb-Pawaz-UU9af-YNMe3-YWSAQ-6-MX-3-SXc-R7-Oh-UVXltqoteg.jpg",
    variants: [
      { size: "500 ml", price: 110, stock: 0 },
      { size: "1 Litre", price: 220, stock: 0 },
    ],
    tags: ["Pooja"],
    price: 110,
    stock: 0,
    sku: "deepam-oil",
    enabled: true,
  },

  // ── Dry Fruits & Nuts ────────────────────────────────────────────────────────
  {
    id: "20000000-0000-0000-0000-000000000001",
    slug: "almonds",
    name: "Almonds",
    tamilName: "பாதாம்",
    category: "dryfruits",
    description: "Premium quality almonds, hand-picked and freshly packed.",
    image: "https://i.ibb.co/1gw6BQv/Chat-GPT-Image-Jun-25-2026-06-33-11-PM.png",
    variants: [
      { size: "250 g", price: 300, stock: 0 },
      { size: "500 g", price: 600, stock: 0 },
      { size: "1 Kg", price: 1200, stock: 0 },
    ],
    tags: ["Nuts", "Premium"],
    price: 300,
    stock: 0,
    sku: "almonds",
    enabled: true,
  },
  {
    id: "20000000-0000-0000-0000-000000000002",
    slug: "cashews",
    name: "Cashews",
    tamilName: "முந்திரி",
    category: "dryfruits",
    description: "Premium quality cashews, hand-picked and freshly packed.",
    image: "https://i.ibb.co/wZjQYNYN/Chat-GPT-Image-Jun-25-2026-06-37-36-PM.png",
    variants: [
      { size: "250 g", price: 300, stock: 0 },
      { size: "500 g", price: 600, stock: 0 },
      { size: "1 Kg", price: 1200, stock: 0 },
    ],
    tags: ["Nuts", "Premium"],
    price: 300,
    stock: 0,
    sku: "cashews",
    enabled: true,
  },
  {
    id: "20000000-0000-0000-0000-000000000003",
    slug: "salted-pistachios",
    name: "Salted Pistachios",
    tamilName: "பிஸ்தா (உப்பு சேர்க்கப்பட்டது)",
    category: "dryfruits",
    description: "Premium quality salted pistachios, hand-picked and freshly packed.",
    image: "https://i.ibb.co/VWV66LZp/Chat-GPT-Image-Jun-25-2026-06-42-56-PM.png",
    variants: [
      { size: "250 g", price: 425, stock: 0 },
      { size: "500 g", price: 850, stock: 0 },
      { size: "1 Kg", price: 1700, stock: 0 },
    ],
    tags: ["Nuts", "Snacks"],
    price: 425,
    stock: 0,
    sku: "salted-pistachios",
    enabled: true,
  },
  {
    id: "20000000-0000-0000-0000-000000000004",
    slug: "unsalted-pistachios",
    name: "Unsalted Pistachios",
    tamilName: "பிஸ்தா",
    category: "dryfruits",
    description: "Premium quality unsalted pistachios, hand-picked and freshly packed.",
    image: "https://i.ibb.co/ZpD9r9sw/Chat-GPT-Image-Jun-25-2026-07-08-15-PM.png",
    variants: [
      { size: "250 g", price: 425, stock: 0 },
      { size: "500 g", price: 850, stock: 0 },
      { size: "1 Kg", price: 1700, stock: 0 },
    ],
    tags: ["Nuts", "Natural"],
    price: 425,
    stock: 0,
    sku: "unsalted-pistachios",
    enabled: true,
  },
  {
    id: "20000000-0000-0000-0000-000000000005",
    slug: "walnuts",
    name: "Walnuts",
    tamilName: "அக்ரூட்",
    category: "dryfruits",
    description: "Premium quality walnuts, hand-picked and freshly packed.",
    image: "https://i.ibb.co/Y4KchSR4/Chat-GPT-Image-Jun-25-2026-07-16-12-PM.png",
    variants: [
      { size: "250 g", price: 425, stock: 0 },
      { size: "500 g", price: 850, stock: 0 },
      { size: "1 Kg", price: 1700, stock: 0 },
    ],
    tags: ["Nuts", "Healthy"],
    price: 425,
    stock: 0,
    sku: "walnuts",
    enabled: true,
  },
  {
    id: "20000000-0000-0000-0000-000000000006",
    slug: "black-raisins",
    name: "Black Raisins (Black Dry Grapes)",
    tamilName: "கருப்பு திராட்சை",
    category: "dryfruits",
    description: "Premium quality black raisins, hand-picked and freshly packed.",
    image: "https://i.ibb.co/qF4LgYNG/Chat-GPT-Image-Jun-25-2026-07-25-44-PM.png",
    variants: [
      { size: "250 g", price: 225, stock: 0 },
      { size: "500 g", price: 450, stock: 0 },
      { size: "1 Kg", price: 900, stock: 0 },
    ],
    tags: ["Dry Fruits"],
    price: 225,
    stock: 0,
    sku: "black-raisins",
    enabled: true,
  },
  {
    id: "20000000-0000-0000-0000-000000000007",
    slug: "yellow-raisins",
    name: "Yellow Raisins (Yellow Dry Grapes)",
    tamilName: "உலர் திராட்சை",
    category: "dryfruits",
    description: "Premium quality yellow raisins, hand-picked and freshly packed.",
    image: "https://i.ibb.co/mrpYdx2b/Chat-GPT-Image-Jun-25-2026-07-21-02-PM.png",
    variants: [
      { size: "250 g", price: 200, stock: 0 },
      { size: "500 g", price: 400, stock: 0 },
      { size: "1 Kg", price: 800, stock: 0 },
    ],
    tags: ["Dry Fruits"],
    price: 200,
    stock: 0,
    sku: "yellow-raisins",
    enabled: true,
  },
  {
    id: "20000000-0000-0000-0000-000000000008",
    slug: "dates",
    name: "Dates",
    tamilName: "பேரிச்சம்பழம்",
    category: "dryfruits",
    description: "Premium quality dates, hand-picked and freshly packed.",
    image: "https://i.ibb.co/dsB16gj5/Chat-GPT-Image-Jun-25-2026-07-28-28-PM.png",
    variants: [
      { size: "250 g", price: 425, stock: 0 },
      { size: "500 g", price: 850, stock: 0 },
      { size: "1 Kg", price: 1700, stock: 0 },
    ],
    tags: ["Dry Fruits", "Energy"],
    price: 425,
    stock: 0,
    sku: "dates",
    enabled: true,
  },
  {
    id: "20000000-0000-0000-0000-000000000009",
    slug: "figs",
    name: "Figs",
    tamilName: "அத்திப்பழம்",
    category: "dryfruits",
    description: "Premium quality figs, hand-picked and freshly packed.",
    image: "https://i.ibb.co/qYmQVbgx/Chat-GPT-Image-Jun-25-2026-07-46-34-PM.png",
    variants: [
      { size: "250 g", price: 425, stock: 0 },
      { size: "500 g", price: 850, stock: 0 },
      { size: "1 Kg", price: 1700, stock: 0 },
    ],
    tags: ["Dry Fruits", "Fiber"],
    price: 425,
    stock: 0,
    sku: "figs",
    enabled: true,
  },

  // ── Palm Products ────────────────────────────────────────────────────────────
  {
    id: "30000000-0000-0000-0000-000000000001",
    slug: "palm-sugar",
    name: "Palm Sugar",
    tamilName: "பனை சர்க்கரை",
    category: "palm-products",
    description:
      "Natural palm sugar made from fresh palm sap. A healthy alternative to refined sugar with a rich caramel-like taste.",
    image: "https://i.ibb.co/jKmvr1m/Chat-GPT-Image-Jun-25-2026-06-23-52-PM.png",
    variants: [
      { size: "500 g", price: 45, stock: 0 },
      { size: "1 Kg", price: 90, stock: 0 },
    ],
    tags: ["Sweetener", "Natural"],
    price: 45,
    stock: 0,
    sku: "palm-sugar",
    enabled: true,
  },
  {
    id: "30000000-0000-0000-0000-000000000002",
    slug: "palm-crystal-sugar",
    name: "Palm Crystal Sugar",
    tamilName: "பனங்கற்கண்டு",
    category: "palm-products",
    description:
      "Pure palm crystal sugar prepared traditionally from palm nectar. Ideal for tea, sweets, and daily use.",
    image: "https://i.ibb.co/CrNW35C/Chat-GPT-Image-Jun-25-2026-10-15-19-PM.png",
    variants: [
      { size: "500 g", price: 350, stock: 0 },
      { size: "1 Kg", price: 700, stock: 0 },
    ],
    tags: ["Sweetener", "Traditional"],
    price: 350,
    stock: 0,
    sku: "palm-crystal-sugar",
    enabled: true,
  },
  {
    id: "30000000-0000-0000-0000-000000000003",
    slug: "palm-jaggery",
    name: "Palm Jaggery",
    tamilName: "பனை வெல்லம் / கருப்பட்டி",
    category: "palm-products",
    description:
      "Traditional palm jaggery made without chemicals or preservatives. Rich in minerals and natural sweetness.",
    image: "https://i.ibb.co/23X07p4G/Chat-GPT-Image-Jun-25-2026-06-14-43-PM.png",
    variants: [
      { size: "500 g", price: 240, stock: 0 },
      { size: "1 Kg", price: 480, stock: 0 },
    ],
    tags: ["Sweetener", "Traditional"],
    price: 240,
    stock: 0,
    sku: "palm-jaggery",
    enabled: true,
  },

  // ── Millets & Traditional Grains ─────────────────────────────────────────────
  {
    id: "40000000-0000-0000-0000-000000000001",
    slug: "varagu",
    name: "Varagu",
    tamilName: "வரகு",
    category: "millets",
    description:
      "A highly nutritious traditional millet rich in fiber and essential minerals. Suitable for healthy meals and diabetic-friendly diets.",
    image: "https://i.ibb.co/dsQkCmpb/varagu.png",
    imageAlt: "Varagu kodo millet in a bowl",
    variants: [
      { size: "500 g", price: 75, stock: 0 },
      { size: "1 Kg", price: 150, stock: 0 },
    ],
    tags: ["Millets"],
    stock: 0,
    price: 75,
    sku: "varagu-500g",
    enabled: true,
    rating: 4.7,
    metaTitle: "Varagu (Kodo Millet) — Millets & Traditional Grains",
    metaDescription:
      "Shop Varagu (Kodo Millet) for a nutritious, fiber-rich traditional grain ideal for healthy and diabetic-friendly meals.",
    structuredData: {
      "@type": "Product",
      name: "Varagu",
      image: ["https://i.ibb.co/dsQkCmpb/varagu.png"],
      description:
        "A highly nutritious traditional millet rich in fiber and essential minerals. Suitable for healthy meals and diabetic-friendly diets.",
      sku: "varagu-500g",
      offers: {
        "@type": "Offer",
        availability: "http://schema.org/InStock",
        priceCurrency: "INR",
        price: 75,
      },
    },
  },
  {
    id: "40000000-0000-0000-0000-000000000002",
    slug: "saamai",
    name: "Saamai",
    tamilName: "சாமை",
    category: "millets",
    description:
      "Light, easy to digest, and naturally rich in nutrients. Ideal for porridge, upma, and everyday healthy cooking.",
    image: "https://i.ibb.co/mFbdCP6T/saamai.png",
    imageAlt: "Saamai little millet grains",
    variants: [
      { size: "500 g", price: 70, stock: 0 },
      { size: "1 Kg", price: 130, stock: 0 },
    ],
    tags: ["Millets"],
    stock: 0,
    price: 70,
    sku: "saamai-500g",
    enabled: true,
    rating: 4.6,
    metaTitle: "Saamai (Little Millet) — Millets & Traditional Grains",
    metaDescription:
      "Ordered Saamai (Little Millet) for light, nutritious cooking. Perfect for upma, porridge, and everyday healthy meals.",
    structuredData: {
      "@type": "Product",
      name: "Saamai",
      image: ["https://i.ibb.co/mFbdCP6T/saamai.png"],
      description:
        "Light, easy to digest, and naturally rich in nutrients. Ideal for porridge, upma, and everyday healthy cooking.",
      sku: "saamai-500g",
      offers: {
        "@type": "Offer",
        availability: "http://schema.org/InStock",
        priceCurrency: "INR",
        price: 70,
      },
    },
  },
  {
    id: "40000000-0000-0000-0000-000000000003",
    slug: "kuthiraivali",
    name: "Kuthiraivali",
    tamilName: "குதிரைவாலி",
    category: "millets",
    description:
      "A wholesome millet with a low glycemic index and high fiber content. Perfect for weight-conscious and health-focused diets.",
    image: "https://i.ibb.co/nqSyM3pD/kuthiraivali.png",
    imageAlt: "Kuthiraivali barnyard millet grains",
    variants: [
      { size: "500 g", price: 75, stock: 0 },
      { size: "1 Kg", price: 150, stock: 0 },
    ],
    tags: ["Millets"],
    stock: 0,
    price: 75,
    sku: "kuthiraivali-500g",
    enabled: true,
    rating: 4.8,
    metaTitle: "Kuthiraivali (Barnyard Millet) — Millets & Traditional Grains",
    metaDescription:
      "Buy Kuthiraivali (Barnyard Millet) for a high-fiber, low glycemic grain that supports healthy and weight-conscious diets.",
    structuredData: {
      "@type": "Product",
      name: "Kuthiraivali",
      image: ["https://i.ibb.co/nqSyM3pD/kuthiraivali.png"],
      description:
        "A wholesome millet with a low glycemic index and high fiber content. Perfect for weight-conscious and health-focused diets.",
      sku: "kuthiraivali-500g",
      offers: {
        "@type": "Offer",
        availability: "http://schema.org/InStock",
        priceCurrency: "INR",
        price: 75,
      },
    },
  },
  {
    id: "40000000-0000-0000-0000-000000000004",
    slug: "thinai",
    name: "Thinai",
    tamilName: "திணை",
    category: "millets",
    description:
      "An ancient millet rich in protein, iron, and dietary fiber. Excellent for both traditional and modern healthy recipes.",
    image: "https://i.ibb.co/v61R0fBS/thinai.png",
    imageAlt: "Thinai foxtail millet grains",
    variants: [
      { size: "500 g", price: 60, stock: 0 },
      { size: "1 Kg", price: 120, stock: 0 },
    ],
    tags: ["Millets"],
    stock: 0,
    price: 60,
    sku: "thinai-500g",
    enabled: true,
    rating: 4.7,
    metaTitle: "Thinai (Foxtail Millet) — Millets & Traditional Grains",
    metaDescription:
      "Purchase Thinai (Foxtail Millet) for a protein-rich, iron-packed pellet ideal for traditional and modern healthy dishes.",
    structuredData: {
      "@type": "Product",
      name: "Thinai",
      image: ["https://i.ibb.co/v61R0fBS/thinai.png"],
      description:
        "An ancient millet rich in protein, iron, and dietary fiber. Excellent for both traditional and modern healthy recipes.",
      sku: "thinai-500g",
      offers: {
        "@type": "Offer",
        availability: "http://schema.org/InStock",
        priceCurrency: "INR",
        price: 60,
      },
    },
  },
  {
    id: "40000000-0000-0000-0000-000000000005",
    slug: "kambu",
    name: "Kambu",
    tamilName: "கம்பு",
    category: "millets",
    description:
      "A nutritious millet packed with energy, calcium, and iron. Commonly used for porridge, rotis, and wholesome meals.",
    image: "https://i.ibb.co/XxKpmcCT/kambu.png",
    imageAlt: "Kambu pearl millet grains",
    variants: [
      { size: "500 g", price: 32, stock: 0 },
      { size: "1 Kg", price: 65, stock: 0 },
    ],
    tags: ["Millets"],
    stock: 0,
    price: 32,
    sku: "kambu-500g",
    enabled: true,
    rating: 4.5,
    metaTitle: "Kambu (Pearl Millet) — Millets & Traditional Grains",
    metaDescription:
      "Order Kambu (Pearl Millet) for a nutrient-packed grain rich in energy, calcium, and iron, perfect for wholesome meals.",
    structuredData: {
      "@type": "Product",
      name: "Kambu",
      image: ["https://i.ibb.co/XxKpmcCT/kambu.png"],
      description:
        "A nutritious millet packed with energy, calcium, and iron. Commonly used for porridge, rotis, and wholesome meals.",
      sku: "kambu-500g",
      offers: {
        "@type": "Offer",
        availability: "http://schema.org/InStock",
        priceCurrency: "INR",
        price: 32,
      },
    },
  },
  {
    id: "40000000-0000-0000-0000-000000000006",
    slug: "kelvaragu",
    name: "Kelvaragu",
    tamilName: "கேழ்வரகு",
    category: "millets",
    description:
      "A superfood millet rich in calcium, iron, and dietary fiber. Ideal for babies, children, and adults as part of a balanced diet.",
    image: "https://i.ibb.co/Z1bWPJTn/kelvaragu.png",
    imageAlt: "Kelvaragu ragi millet grains",
    variants: [
      { size: "500 g", price: 35, stock: 0 },
      { size: "1 Kg", price: 70, stock: 0 },
    ],
    tags: ["Millets"],
    stock: 0,
    price: 35,
    sku: "kelvaragu-500g",
    enabled: true,
    rating: 4.8,
    metaTitle: "Kelvaragu (Finger Millet) — Millets & Traditional Grains",
    metaDescription:
      "Buy Kelvaragu (Finger Millet) for a calcium-rich superfood millet perfect for all ages and healthy diets.",
    structuredData: {
      "@type": "Product",
      name: "Kelvaragu",
      image: ["https://i.ibb.co/Z1bWPJTn/kelvaragu.png"],
      description:
        "A superfood millet rich in calcium, iron, and dietary fiber. Ideal for babies, children, and adults as part of a balanced diet.",
      sku: "kelvaragu-500g",
      offers: {
        "@type": "Offer",
        availability: "http://schema.org/InStock",
        priceCurrency: "INR",
        price: 35,
      },
    },
  },
  {
    id: "40000000-0000-0000-0000-000000000007",
    slug: "mappillai-samba-rice",
    name: "Mappillai Samba Rice",
    tamilName: "மாப்பிள்ளை சம்பா அரிசி",
    category: "millets",
    description:
      "A traditional red rice variety known for its strength-giving properties, rich fiber content, and natural nutrients. Ideal for healthy meals and traditional South Indian cooking.",
    image: "https://i.ibb.co/dwdfn1cQ/mappillai-samba-rice.png",
    imageAlt: "Mappillai Samba red rice grains",
    variants: [
      { size: "500 g", price: 80, stock: 0 },
      { size: "1 Kg", price: 160, stock: 0 },
    ],
    tags: ["Traditional Rice"],
    stock: 0,
    price: 80,
    sku: "mappillai-samba-rice-500g",
    enabled: true,
    rating: 4.7,
    metaTitle: "Mappillai Samba Rice — Millets & Traditional Grains",
    metaDescription:
      "Shop Mappillai Samba Rice, a traditional red rice rich in fiber and nutrients, perfect for healthy South Indian meals.",
    structuredData: {
      "@type": "Product",
      name: "Mappillai Samba Rice",
      image: ["https://i.ibb.co/dwdfn1cQ/mappillai-samba-rice.png"],
      description:
        "A traditional red rice variety known for its strength-giving properties, rich fiber content, and natural nutrients. Ideal for healthy meals and traditional South Indian cooking.",
      sku: "mappillai-samba-rice-500g",
      offers: {
        "@type": "Offer",
        availability: "http://schema.org/InStock",
        priceCurrency: "INR",
        price: 80,
      },
    },
  },
  {
    id: "40000000-0000-0000-0000-000000000008",
    slug: "karuppu-kavuni-rice",
    name: "Karuppu Kavuni Rice",
    tamilName: "கருப்பு கவுனி அரிசி",
    category: "millets",
    description:
      "A rare premium black rice variety rich in antioxidants, iron, and natural nutrients. Traditionally valued for its unique taste and health benefits.",
    image: "https://i.ibb.co/Qj1XZGD5/karuppu-kavuni-rice.png",
    imageAlt: "Karuppu Kavuni black rice grains",
    variants: [
      { size: "500 g", price: 100, stock: 0 },
      { size: "1 Kg", price: 200, stock: 0 },
    ],
    tags: ["Premium Rice"],
    stock: 0,
    price: 100,
    sku: "karuppu-kavuni-rice-500g",
    enabled: true,
    rating: 4.9,
    metaTitle: "Karuppu Kavuni Rice — Millets & Traditional Grains",
    metaDescription:
      "Discover Karuppu Kavuni Rice, a premium black rice rich in antioxidants and natural nutrients for healthy eating.",
    structuredData: {
      "@type": "Product",
      name: "Karuppu Kavuni Rice",
      image: ["https://i.ibb.co/Qj1XZGD5/karuppu-kavuni-rice.png"],
      description:
        "A rare premium black rice variety rich in antioxidants, iron, and natural nutrients. Traditionally valued for its unique taste and health benefits.",
      sku: "karuppu-kavuni-rice-500g",
      offers: {
        "@type": "Offer",
        availability: "http://schema.org/InStock",
        priceCurrency: "INR",
        price: 100,
      },
    },
  },
  {
    id: "40000000-0000-0000-0000-000000000009",
    slug: "sivappu-arisi",
    name: "Sivappu Arisi",
    tamilName: "சிவப்பு அரிசி",
    category: "millets",
    description:
      "A wholesome traditional red rice rich in fiber, minerals, and natural nutrients. Perfect for healthy everyday meals and traditional South Indian recipes.",
    image: "https://i.ibb.co/BVgQ7GcX/sivappu-arisi.png",
    imageAlt: "Sivappu Arisi red rice grains",
    variants: [
      { size: "500 g", price: 60, stock: 0 },
      { size: "1 Kg", price: 120, stock: 0 },
    ],
    tags: ["Traditional Rice"],
    stock: 0,
    price: 60,
    sku: "sivappu-arisi-500g",
    enabled: true,
    rating: 4.6,
    metaTitle: "Sivappu Arisi (Red Rice) — Millets & Traditional Grains",
    metaDescription:
      "Buy Sivappu Arisi, a traditional red rice full of fiber and minerals for healthy everyday South Indian cooking.",
  },

  // ── Natural Honey ────────────────────────────────────────────────────────────
  {
    id: "50000000-0000-0000-0000-000000000001",
    slug: "malai-then",
    name: "Malai Then",
    tamilName: "மலைத் தேன்",
    category: "honey",
    description:
      "Pure natural hill honey collected from bees in forest and mountain regions. Naturally rich in enzymes, antioxidants, vitamins, and minerals.",
    image: "https://i.ibb.co/7QC8b2x/honey-jar-2.jpg",
    imageAlt: "Malai Then hill honey with wooden dipper",
    variants: [
      { size: "250 g", price: 400, stock: 0 },
      { size: "500 g", price: 800, stock: 0 },
    ],
    tags: ["Premium", "Organic"],
    stock: 0,
    price: 400,
    sku: "malai-then-250g",
    enabled: true,
    rating: 4.9,
  },
];