import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL || 'https://placeholder.supabase.co';
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || 'placeholder';
const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: { autoRefreshToken: false, persistSession: false },
});

export const SEED_PRODUCTS = [
  // Cold Pressed Oils
  {
    id: '10000000-0000-0000-0000-000000000001',
    slug: 'groundnut-oil',
    name: 'Groundnut Oil',
    tamil_name: 'கடலை எண்ணெய்',
    category: 'oils',
    price: 120,
    stock: 0,
    sku: 'groundnut-oil',
    image: 'https://i.ibb.co/tM14KvL4/Chat-GPT-Image-Jun-24-2026-03-53-07-PM.png',
    images: ['https://i.ibb.co/tM14KvL4/Chat-GPT-Image-Jun-24-2026-03-53-07-PM.png'],
    tags: ['Best Seller', 'Popular'],
    description: 'Traditional cold-pressed groundnut oil extracted without chemicals. Rich in antioxidants and perfect for everyday cooking.',
    variants: [
      { size: '500 ml', price: 120, stock: 0 },
      { size: '1 Litre', price: 240, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '10000000-0000-0000-0000-000000000002',
    slug: 'sesame-oil',
    name: 'Sesame Oil',
    tamil_name: 'நல்லெண்ணெய்',
    category: 'oils',
    price: 190,
    stock: 0,
    sku: 'sesame-oil',
    image: 'https://i.ibb.co/bMdwm3v9/Image-1-1.webp',
    images: ['https://i.ibb.co/bMdwm3v9/Image-1-1.webp'],
    tags: ['Popular'],
    description: 'Wood-pressed sesame oil rich in calcium, vitamins and healthy fats. Ideal for cooking and traditional uses.',
    variants: [
      { size: '500 ml', price: 190, stock: 0 },
      { size: '1 Litre', price: 370, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '10000000-0000-0000-0000-000000000003',
    slug: 'coconut-oil',
    name: 'Coconut Oil',
    tamil_name: 'தேங்காய் எண்ணெய்',
    category: 'oils',
    price: 200,
    stock: 0,
    sku: 'coconut-oil',
    image: 'https://i.ibb.co/pBSC9w8t/Chat-GPT-Image-Jun-24-2026-07-00-57-PM.png',
    images: ['https://i.ibb.co/pBSC9w8t/Chat-GPT-Image-Jun-24-2026-07-00-57-PM.png'],
    tags: ['New'],
    description: 'Pure cold-pressed coconut oil from fresh coconuts. Excellent for cooking, skin care and hair care.',
    variants: [
      { size: '500 ml', price: 200, stock: 0 },
      { size: '1 Litre', price: 390, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '10000000-0000-0000-0000-000000000004',
    slug: 'castor-oil',
    name: 'Castor Oil',
    tamil_name: 'ஆமணக்கு எண்ணெய்',
    category: 'oils',
    price: 90,
    stock: 0,
    sku: 'castor-oil',
    image: 'https://i.ibb.co/7d71yWkt/Chat-GPT-Image-Jun-25-2026-10-17-30-AM.png',
    images: ['https://i.ibb.co/7d71yWkt/Chat-GPT-Image-Jun-25-2026-10-17-30-AM.png'],
    tags: ['Traditional'],
    description: 'Natural castor oil known for hair growth and medicinal benefits.',
    variants: [
      { size: '250 ml', price: 90, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '10000000-0000-0000-0000-000000000005',
    slug: 'mustard-oil',
    name: 'Mustard Oil',
    tamil_name: 'கடுகு எண்ணெய்',
    category: 'oils',
    price: 75,
    stock: 0,
    sku: 'mustard-oil',
    image: 'https://i.ibb.co/cS2NX06C/Chat-GPT-Image-Jun-25-2026-06-43-30-PM.png',
    images: ['https://i.ibb.co/cS2NX06C/Chat-GPT-Image-Jun-25-2026-06-43-30-PM.png'],
    tags: ['Traditional'],
    description: 'Traditional mustard oil rich in omega fatty acids with natural flavour.',
    variants: [
      { size: '250 ml', price: 75, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '10000000-0000-0000-0000-000000000006',
    slug: 'neem-oil',
    name: 'Neem Oil',
    tamil_name: 'வேப்ப எண்ணெய்',
    category: 'oils',
    price: 100,
    stock: 0,
    sku: 'neem-oil',
    image: 'https://i.ibb.co/tw2NqHCD/Chat-GPT-Image-Jun-25-2026-06-35-55-PM.png',
    images: ['https://i.ibb.co/tw2NqHCD/Chat-GPT-Image-Jun-25-2026-06-35-55-PM.png'],
    tags: ['Traditional'],
    description: '100% pure neem oil for agricultural and external applications.',
    variants: [
      { size: '250 ml', price: 100, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '10000000-0000-0000-0000-000000000007',
    slug: 'deepam-oil',
    name: 'Deepam Oil',
    tamil_name: 'தீபம் எண்ணெய்',
    category: 'oils',
    price: 110,
    stock: 0,
    sku: 'deepam-oil',
    image: 'https://i.ibb.co/gZY8TM8M/remove-the-seed-image-Rb-Pawaz-UU9af-YNMe3-YWSAQ-6-MX-3-SXc-R7-Oh-UVXltqoteg.jpg',
    images: ['https://i.ibb.co/gZY8TM8M/remove-the-seed-image-Rb-Pawaz-UU9af-YNMe3-YWSAQ-6-MX-3-SXc-R7-Oh-UVXltqoteg.jpg'],
    tags: ['Traditional'],
    description: 'Traditional deepam oil for ritual and everyday uses, made with care for ceremonial lighting.',
    variants: [
      { size: '500 ml', price: 110, stock: 0 },
      { size: '1 Litre', price: 220, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },

  // Dry Fruits & Nuts
  {
    id: '20000000-0000-0000-0000-000000000001',
    slug: 'almonds',
    name: 'Almonds',
    tamil_name: 'பாதாம்',
    category: 'dryfruits',
    price: 300,
    stock: 0,
    sku: 'almonds',
    image: 'https://i.ibb.co/1gw6BQv/Chat-GPT-Image-Jun-25-2026-06-33-11-PM.png',
    images: ['https://i.ibb.co/1gw6BQv/Chat-GPT-Image-Jun-25-2026-06-33-11-PM.png'],
    tags: ['Popular'],
    description: 'Premium quality almonds, hand-picked and freshly packed.',
    variants: [
      { size: '250 g', price: 300, stock: 0 },
      { size: '500 g', price: 600, stock: 0 },
      { size: '1 Kg', price: 1200, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '20000000-0000-0000-0000-000000000002',
    slug: 'cashews',
    name: 'Cashews',
    tamil_name: 'முந்திரி',
    category: 'dryfruits',
    price: 300,
    stock: 0,
    sku: 'cashews',
    image: 'https://i.ibb.co/wZjQYNYN/Chat-GPT-Image-Jun-25-2026-06-37-36-PM.png',
    images: ['https://i.ibb.co/wZjQYNYN/Chat-GPT-Image-Jun-25-2026-06-37-36-PM.png'],
    tags: ['Popular'],
    description: 'Premium quality cashews, hand-picked and freshly packed.',
    variants: [
      { size: '250 g', price: 300, stock: 0 },
      { size: '500 g', price: 600, stock: 0 },
      { size: '1 Kg', price: 1200, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '20000000-0000-0000-0000-000000000003',
    slug: 'salted-pistachios',
    name: 'Salted Pistachios',
    tamil_name: 'பிஸ்தா (உப்பு சேர்க்கப்பட்டது)',
    category: 'dryfruits',
    price: 425,
    stock: 0,
    sku: 'salted-pistachios',
    image: 'https://i.ibb.co/VWV66LZp/Chat-GPT-Image-Jun-25-2026-06-42-56-PM.png',
    images: ['https://i.ibb.co/VWV66LZp/Chat-GPT-Image-Jun-25-2026-06-42-56-PM.png'],
    tags: ['Premium'],
    description: 'Premium quality salted pistachios, hand-picked and freshly packed.',
    variants: [
      { size: '250 g', price: 425, stock: 0 },
      { size: '500 g', price: 850, stock: 0 },
      { size: '1 Kg', price: 1700, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '20000000-0000-0000-0000-000000000004',
    slug: 'unsalted-pistachios',
    name: 'Unsalted Pistachios',
    tamil_name: 'பிஸ்தா',
    category: 'dryfruits',
    price: 425,
    stock: 0,
    sku: 'unsalted-pistachios',
    image: 'https://i.ibb.co/ZpD9r9sw/Chat-GPT-Image-Jun-25-2026-07-08-15-PM.png',
    images: ['https://i.ibb.co/ZpD9r9sw/Chat-GPT-Image-Jun-25-2026-07-08-15-PM.png'],
    tags: ['Premium'],
    description: 'Premium quality unsalted pistachios, hand-picked and freshly packed.',
    variants: [
      { size: '250 g', price: 425, stock: 0 },
      { size: '500 g', price: 850, stock: 0 },
      { size: '1 Kg', price: 1700, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '20000000-0000-0000-0000-000000000005',
    slug: 'walnuts',
    name: 'Walnuts',
    tamil_name: 'அக்ரூட்',
    category: 'dryfruits',
    price: 425,
    stock: 0,
    sku: 'walnuts',
    image: 'https://i.ibb.co/Y4KchSR4/Chat-GPT-Image-Jun-25-2026-07-16-12-PM.png',
    images: ['https://i.ibb.co/Y4KchSR4/Chat-GPT-Image-Jun-25-2026-07-16-12-PM.png'],
    tags: ['Premium'],
    description: 'Premium quality walnuts, hand-picked and freshly packed.',
    variants: [
      { size: '250 g', price: 425, stock: 0 },
      { size: '500 g', price: 850, stock: 0 },
      { size: '1 Kg', price: 1700, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '20000000-0000-0000-0000-000000000006',
    slug: 'black-raisins',
    name: 'Black Raisins',
    tamil_name: 'கருப்பு திராட்சை',
    category: 'dryfruits',
    price: 225,
    stock: 0,
    sku: 'black-raisins',
    image: 'https://i.ibb.co/qF4LgYNG/Chat-GPT-Image-Jun-25-2026-07-25-44-PM.png',
    images: ['https://i.ibb.co/qF4LgYNG/Chat-GPT-Image-Jun-25-2026-07-25-44-PM.png'],
    tags: ['Healthy'],
    description: 'Premium quality black raisins, hand-picked and freshly packed.',
    variants: [
      { size: '250 g', price: 225, stock: 0 },
      { size: '500 g', price: 450, stock: 0 },
      { size: '1 Kg', price: 900, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '20000000-0000-0000-0000-000000000007',
    slug: 'yellow-raisins',
    name: 'Yellow Raisins',
    tamil_name: 'உலர் திராட்சை',
    category: 'dryfruits',
    price: 200,
    stock: 0,
    sku: 'yellow-raisins',
    image: 'https://i.ibb.co/mrpYdx2b/Chat-GPT-Image-Jun-25-2026-07-21-02-PM.png',
    images: ['https://i.ibb.co/mrpYdx2b/Chat-GPT-Image-Jun-25-2026-07-21-02-PM.png'],
    tags: ['Healthy'],
    description: 'Premium quality yellow raisins, hand-picked and freshly packed.',
    variants: [
      { size: '250 g', price: 200, stock: 0 },
      { size: '500 g', price: 400, stock: 0 },
      { size: '1 Kg', price: 800, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '20000000-0000-0000-0000-000000000008',
    slug: 'dates',
    name: 'Dates',
    tamil_name: 'பேரிச்சம்பழம்',
    category: 'dryfruits',
    price: 425,
    stock: 0,
    sku: 'dates',
    image: 'https://i.ibb.co/dsB16gj5/Chat-GPT-Image-Jun-25-2026-07-28-28-PM.png',
    images: ['https://i.ibb.co/dsB16gj5/Chat-GPT-Image-Jun-25-2026-07-28-28-PM.png'],
    tags: ['Healthy'],
    description: 'Premium quality dates, hand-picked and freshly packed.',
    variants: [
      { size: '250 g', price: 425, stock: 0 },
      { size: '500 g', price: 850, stock: 0 },
      { size: '1 Kg', price: 1700, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '20000000-0000-0000-0000-000000000009',
    slug: 'figs',
    name: 'Figs',
    tamil_name: 'அத்திப்பழம்',
    category: 'dryfruits',
    price: 425,
    stock: 0,
    sku: 'figs',
    image: 'https://i.ibb.co/qYmQVbgx/Chat-GPT-Image-Jun-25-2026-07-46-34-PM.png',
    images: ['https://i.ibb.co/qYmQVbgx/Chat-GPT-Image-Jun-25-2026-07-46-34-PM.png'],
    tags: ['Premium'],
    description: 'Premium quality figs, hand-picked and freshly packed.',
    variants: [
      { size: '250 g', price: 425, stock: 0 },
      { size: '500 g', price: 850, stock: 0 },
      { size: '1 Kg', price: 1700, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },

  // Palm Products
  {
    id: '30000000-0000-0000-0000-000000000001',
    slug: 'palm-sugar',
    name: 'Palm Sugar',
    tamil_name: 'பனை சர்க்கரை',
    category: 'palm-products',
    price: 45,
    stock: 0,
    sku: 'palm-sugar',
    image: 'https://i.ibb.co/jKmvr1m/Chat-GPT-Image-Jun-25-2026-06-23-52-PM.png',
    images: ['https://i.ibb.co/jKmvr1m/Chat-GPT-Image-Jun-25-2026-06-23-52-PM.png'],
    tags: ['Traditional', 'Organic'],
    description: 'Natural palm sugar made from fresh palm sap. A healthy alternative to refined sugar with a rich caramel-like taste.',
    variants: [
      { size: '500 g', price: 45, stock: 0 },
      { size: '1 Kg', price: 90, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '30000000-0000-0000-0000-000000000002',
    slug: 'palm-crystal-sugar',
    name: 'Palm Crystal Sugar',
    tamil_name: 'பனங்கற்கண்டு',
    category: 'palm-products',
    price: 350,
    stock: 0,
    sku: 'palm-crystal-sugar',
    image: 'https://i.ibb.co/CrNW35C/Chat-GPT-Image-Jun-25-2026-10-15-19-PM.png',
    images: ['https://i.ibb.co/CrNW35C/Chat-GPT-Image-Jun-25-2026-10-15-19-PM.png'],
    tags: ['Traditional', 'Organic'],
    description: 'Pure palm crystal sugar prepared traditionally from palm nectar. Ideal for tea, sweets, and daily use.',
    variants: [
      { size: '500 g', price: 350, stock: 0 },
      { size: '1 Kg', price: 700, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '30000000-0000-0000-0000-000000000003',
    slug: 'palm-jaggery',
    name: 'Palm Jaggery',
    tamil_name: 'பனை வெல்லம் / கருப்பட்டி',
    category: 'palm-products',
    price: 240,
    stock: 0,
    sku: 'palm-jaggery',
    image: 'https://i.ibb.co/23X07p4G/Chat-GPT-Image-Jun-25-2026-06-14-43-PM.png',
    images: ['https://i.ibb.co/23X07p4G/Chat-GPT-Image-Jun-25-2026-06-14-43-PM.png'],
    tags: ['Traditional', 'Organic'],
    description: 'Traditional palm jaggery made without chemicals or preservatives. Rich in minerals and natural sweetness.',
    variants: [
      { size: '500 g', price: 240, stock: 0 },
      { size: '1 Kg', price: 480, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },

  // Millets & Grains
  {
    id: '40000000-0000-0000-0000-000000000001',
    slug: 'varagu',
    name: 'Varagu',
    tamil_name: 'வரகு',
    category: 'millets',
    price: 75,
    stock: 0,
    sku: 'varagu-500g',
    image: 'https://i.ibb.co/dsQkCmpb/varagu.png',
    images: ['https://i.ibb.co/dsQkCmpb/varagu.png'],
    tags: ['Millets', 'Healthy'],
    description: 'A highly nutritious traditional millet rich in fiber and essential minerals. Suitable for healthy meals and diabetic-friendly diets.',
    variants: [
      { size: '500 g', price: 75, stock: 0 },
      { size: '1 Kg', price: 150, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '40000000-0000-0000-0000-000000000002',
    slug: 'saamai',
    name: 'Saamai',
    tamil_name: 'சாமை',
    category: 'millets',
    price: 70,
    stock: 0,
    sku: 'saamai-500g',
    image: 'https://i.ibb.co/mFbdCP6T/saamai.png',
    images: ['https://i.ibb.co/mFbdCP6T/saamai.png'],
    tags: ['Millets', 'Healthy'],
    description: 'Light, easy to digest, and naturally rich in nutrients. Ideal for porridge, upma, and everyday healthy cooking.',
    variants: [
      { size: '500 g', price: 70, stock: 0 },
      { size: '1 Kg', price: 130, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '40000000-0000-0000-0000-000000000003',
    slug: 'kuthiraivali',
    name: 'Kuthiraivali',
    tamil_name: 'குதிரைவாலி',
    category: 'millets',
    price: 75,
    stock: 0,
    sku: 'kuthiraivali-500g',
    image: 'https://i.ibb.co/nqSyM3pD/kuthiraivali.png',
    images: ['https://i.ibb.co/nqSyM3pD/kuthiraivali.png'],
    tags: ['Millets', 'Healthy'],
    description: 'A wholesome millet with a low glycemic index and high fiber content. Perfect for weight-conscious and health-focused diets.',
    variants: [
      { size: '500 g', price: 75, stock: 0 },
      { size: '1 Kg', price: 150, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '40000000-0000-0000-0000-000000000004',
    slug: 'thinai',
    name: 'Thinai',
    tamil_name: 'திணை',
    category: 'millets',
    price: 60,
    stock: 0,
    sku: 'thinai-500g',
    image: 'https://i.ibb.co/v61R0fBS/thinai.png',
    images: ['https://i.ibb.co/v61R0fBS/thinai.png'],
    tags: ['Millets', 'Healthy'],
    description: 'An ancient millet rich in protein, iron, and dietary fiber. Excellent for both traditional and modern healthy recipes.',
    variants: [
      { size: '500 g', price: 60, stock: 0 },
      { size: '1 Kg', price: 120, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '40000000-0000-0000-0000-000000000005',
    slug: 'kambu',
    name: 'Kambu',
    tamil_name: 'கம்பு',
    category: 'millets',
    price: 32,
    stock: 0,
    sku: 'kambu-500g',
    image: 'https://i.ibb.co/XxKpmcCT/kambu.png',
    images: ['https://i.ibb.co/XxKpmcCT/kambu.png'],
    tags: ['Millets', 'Healthy'],
    description: 'A nutritious millet packed with energy, calcium, and iron. Commonly used for porridge, rotis, and wholesome meals.',
    variants: [
      { size: '500 g', price: 32, stock: 0 },
      { size: '1 Kg', price: 65, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '40000000-0000-0000-0000-000000000006',
    slug: 'kelvaragu',
    name: 'Kelvaragu',
    tamil_name: 'கேழ்வரகு',
    category: 'millets',
    price: 35,
    stock: 0,
    sku: 'kelvaragu-500g',
    image: 'https://i.ibb.co/Z1bWPJTn/kelvaragu.png',
    images: ['https://i.ibb.co/Z1bWPJTn/kelvaragu.png'],
    tags: ['Millets', 'Healthy'],
    description: 'A superfood millet rich in calcium, iron, and dietary fiber. Ideal for babies, children, and adults as part of a balanced diet.',
    variants: [
      { size: '500 g', price: 35, stock: 0 },
      { size: '1 Kg', price: 70, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '40000000-0000-0000-0000-000000000007',
    slug: 'mappillai-samba-rice',
    name: 'Mappillai Samba Rice',
    tamil_name: 'மாப்பிள்ளை சம்பா அரிசி',
    category: 'millets',
    price: 80,
    stock: 0,
    sku: 'mappillai-samba-rice-500g',
    image: 'https://i.ibb.co/dwdfn1cQ/mappillai-samba-rice.png',
    images: ['https://i.ibb.co/dwdfn1cQ/mappillai-samba-rice.png'],
    tags: ['Traditional Rice'],
    description: 'A traditional red rice variety known for its strength-giving properties, rich fiber content, and natural nutrients. Ideal for healthy meals and traditional South Indian cooking.',
    variants: [
      { size: '500 g', price: 80, stock: 0 },
      { size: '1 Kg', price: 160, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '40000000-0000-0000-0000-000000000008',
    slug: 'karuppu-kavuni-rice',
    name: 'Karuppu Kavuni Rice',
    tamil_name: 'கருப்பு கவுனி அரிசி',
    category: 'millets',
    price: 100,
    stock: 0,
    sku: 'karuppu-kavuni-rice-500g',
    image: 'https://i.ibb.co/Qj1XZGD5/karuppu-kavuni-rice.png',
    images: ['https://i.ibb.co/Qj1XZGD5/karuppu-kavuni-rice.png'],
    tags: ['Premium Rice'],
    description: 'A rare premium black rice variety rich in antioxidants, iron, and natural nutrients. Traditionally valued for its unique taste and health benefits.',
    variants: [
      { size: '500 g', price: 100, stock: 0 },
      { size: '1 Kg', price: 200, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
  {
    id: '40000000-0000-0000-0000-000000000009',
    slug: 'sivappu-arisi',
    name: 'Sivappu Arisi',
    tamil_name: 'சிவப்பு அரிசி',
    category: 'millets',
    price: 60,
    stock: 0,
    sku: 'sivappu-arisi-500g',
    image: 'https://i.ibb.co/BVgQ7GcX/sivappu-arisi.png',
    images: ['https://i.ibb.co/BVgQ7GcX/sivappu-arisi.png'],
    tags: ['Traditional Rice'],
    description: 'A wholesome traditional red rice rich in fiber, minerals, and natural nutrients. Perfect for healthy everyday meals and traditional South Indian recipes.',
    variants: [
      { size: '500 g', price: 60, stock: 0 },
      { size: '1 Kg', price: 120, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },

  // Natural Honey
  {
    id: '50000000-0000-0000-0000-000000000001',
    slug: 'malai-then',
    name: 'Malai Then',
    tamil_name: 'மலைத் தேன்',
    category: 'honey',
    price: 400,
    stock: 0,
    sku: 'malai-then-250g',
    image: 'https://i.ibb.co/7QC8b2x/honey-jar-2.jpg',
    images: ['https://i.ibb.co/7QC8b2x/honey-jar-2.jpg'],
    tags: ['Premium', 'Organic'],
    description: 'Pure natural hill honey collected from bees in forest and mountain regions. Naturally rich in enzymes, antioxidants, vitamins, and minerals.',
    variants: [
      { size: '250 g', price: 400, stock: 0 },
      { size: '500 g', price: 800, stock: 0 },
    ],
    is_active: true,
    enabled: true,
  },
];

export async function seedDB() {
  if (!process.env.SUPABASE_URL || process.env.SUPABASE_URL.includes('placeholder')) {
    console.log('[Seed] Supabase URL not configured, skipping seed.');
    return;
  }

  try {
    console.log(`[Seed] Starting database seed for ${SEED_PRODUCTS.length} products...`);

    let seeded = 0;
    for (const product of SEED_PRODUCTS) {
      const { error } = await supabase
        .from('products')
        .upsert(product, { onConflict: 'slug', ignoreDuplicates: false });

      if (error) {
        console.error(`[Seed] Error seeding product ${product.slug}:`, error.message);
      } else {
        seeded++;
      }
    }
    console.log(`[Seed] ✅ Seeded ${seeded}/${SEED_PRODUCTS.length} products`);

    // Seed default coupon
    const { error: couponErr } = await supabase
      .from('coupons')
      .upsert({ code: 'SVOM10', discount_pct: 10, enabled: true }, { onConflict: 'code' });

    if (!couponErr) {
      console.log('[Seed] ✅ Coupon SVOM10 ready');
    }

    console.log('[Seed] 🌱 Database seeding complete!');
  } catch (err) {
    console.error('[Seed] Seed failed:', err.message);
  }
}

if (process.argv[1]?.endsWith('seed.js')) {
  seedDB().then(() => process.exit(0)).catch(() => process.exit(1));
}
